# Generated by Django 4.2.3 on 2023-07-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('I', 'Titulaire'), ('T', 'Piégeur'), ('C', 'Contrôleur')], default='T', max_length=1)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('zip_code', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('approval_ref', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
